import fs from "fs";
import { songList } from "./songList.js";
import { searchItunes, titleMatches, artistMatches } from "../utils/itunes.js";

const PROGRESS_FILE = "./scripts/attempted.json";

function wait(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function shuffle(array) {
  const result = [...array];
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}

function splitIntoTiers(songs) {
  const shuffled = shuffle(songs);
  const third = Math.ceil(shuffled.length / 3);
  return {
    easy: shuffled.slice(0, third),
    medium: shuffled.slice(third, third * 2),
    hard: shuffled.slice(third * 2),
  };
}

function parseQuery(query) {
  const [title, ...rest] = query.split(" - ");
  return { title: title.trim(), artist: rest.join(" - ").trim() };
}

function loadAttempted() {
  try {
    const raw = fs.readFileSync(PROGRESS_FILE, "utf-8");
    return new Set(JSON.parse(raw));
  } catch {
    return new Set();
  }
}

function saveAttempted(attemptedSet) {
  fs.writeFileSync(PROGRESS_FILE, JSON.stringify([...attemptedSet], null, 2));
}

const maxSongs = process.argv[2] ? parseInt(process.argv[2], 10) : Infinity;

async function buildBank() {
  let bank = {};
  try {
    const existing = await import("../data/songs.js");
    bank = existing.songBank;
    console.log("Loaded existing songs.js — new results will be merged in.");
  } catch {
    console.log("No existing songs.js found — starting fresh.");
  }

  const attempted = loadAttempted();
  console.log(`${attempted.size} song(s) already attempted in previous runs — those will be skipped.\n`);

  let songsProcessed = 0;

  for (const genre of Object.keys(songList)) {
    if (songsProcessed >= maxSongs) break;

    const songs = songList[genre];
    const tiers = splitIntoTiers(songs);

    if (!bank[genre]) {
      bank[genre] = { easy: [], medium: [], hard: [] };
    }

    let genreHeaderPrinted = false;

    for (const tierName of ["easy", "medium", "hard"]) {
      for (const query of tiers[tierName]) {
        if (attempted.has(query)) continue; // already tried in a previous run
        if (songsProcessed >= maxSongs) break;

        if (!genreHeaderPrinted) {
          console.log(`\n--- ${genre} ---`);
          genreHeaderPrinted = true;
        }

        console.log(`[${tierName}] Searching: ${query}`);
        const { title, artist } = parseQuery(query);

        try {
          const candidates = await searchItunes(query, 10);
          const match = candidates.find(
            (c) => titleMatches(c.name, title) && artistMatches(c.artist, artist)
          );

          if (!match) {
            console.log(`  ⚠ No confident match for "${query}" — skipping`);
          } else {
            const alreadyExists = bank[genre][tierName].some((s) => s.id === match.id);
            if (!alreadyExists) {
              bank[genre][tierName].push({ ...match, clipStart: 0 });
            }
            console.log(`  ✓ Found: ${match.name} — ${match.artist}`);
          }
        } catch (err) {
          console.log(`  ⚠ Error searching "${query}": ${err.message}`);
        }

        attempted.add(query);
        songsProcessed++;
        await wait(6000);
      }
      if (songsProcessed >= maxSongs) break;
    }
  }

  const output = `// Auto-generated by scripts/buildSongBank.js — edit songList.js and re-run to update.\nexport const songBank = ${JSON.stringify(bank, null, 2)};\n`;
  fs.writeFileSync("./data/songs.js", output);
  saveAttempted(attempted);

  console.log(`\n✅ Done! Processed ${songsProcessed} new song(s) this run. backend/data/songs.js has been updated.`);
}

buildBank();