export const songList = {
  Pop: [
  "Blinding Lights - The Weeknd",
  "Shape of You - Ed Sheeran",
  "Sunflower - Post Malone & Swae Lee",
  "Dance Monkey - Tones and I",
  "Someone You Loved - Lewis Capaldi",
  "Believer - Imagine Dragons",
  "Rockstar - Post Malone ft. 21 Savage",
  "Closer - The Chainsmokers ft. Halsey",
  "Perfect - Ed Sheeran",
  "Circles - Post Malone",
  "Stay - The Kid LAROI & Justin Bieber",
  "Watermelon Sugar - Harry Styles",
  "As It Was - Harry Styles",
  "Levitating - Dua Lipa",
  "Bad Guy - Billie Eilish",
  "Old Town Road - Lil Nas X ft. Billy Ray Cyrus",
  "Señorita - Shawn Mendes & Camila Cabello",
  "Havana - Camila Cabello ft. Young Thug",
  "Sweater Weather - The Neighbourhood",
  "Thinking Out Loud - Ed Sheeran",
  "Roses - SAINt JHN",
  "Lucid Dreams - Juice WRLD",
  "Say You Won't Let Go - James Arthur",
  "Attention - Charlie Puth",
  "In the End - Linkin Park",
  "Riptide - Vance Joy",
  "Counting Stars - OneRepublic",
  "Radioactive - Imagine Dragons",
  "Photograph - Ed Sheeran",
  "Numb - Linkin Park",
  "Cruel Summer - Taylor Swift",
  "Anti-Hero - Taylor Swift",
  "Flowers - Miley Cyrus",
  "Espresso - Sabrina Carpenter",
  "Good 4 U - Olivia Rodrigo",
  "drivers license - Olivia Rodrigo",
  "Peaches - Justin Bieber ft. Daniel Caesar & Giveon",
  "Uptown Funk - Mark Ronson ft. Bruno Mars",
  "Happier - Marshmello ft. Bastille",
  "Something Just Like This - The Chainsmokers & Coldplay",
  "Wake Me Up - Avicii",
  "Faded - Alan Walker",
  "Despacito - Luis Fonsi ft. Daddy Yankee",
  "One Dance - Drake ft. WizKid & Kyla",
  "New Rules - Dua Lipa",
  "Don't Start Now - Dua Lipa",
  "God's Plan - Drake",
  "Girls Like You - Maroon 5 ft. Cardi B",
  "Sicko Mode - Travis Scott",
  "Starboy - The Weeknd ft. Daft Punk",
    ],
  Rap: [
  "Lose Yourself - Eminem",
  "In Da Club - 50 Cent",
  "HUMBLE. - Kendrick Lamar",
  "God's Plan - Drake",
  "Empire State of Mind - Jay-Z ft. Alicia Keys",
  "Stronger - Kanye West",
  "Lucid Dreams - Juice WRLD",
  "Sicko Mode - Travis Scott",
  "Mo Bamba - Sheck Wes",
  "Old Town Road - Lil Nas X ft. Billy Ray Cyrus",
  "Bodak Yellow - Cardi B",
  "The Box - Roddy Ricch",
  "No Role Modelz - J. Cole",
  "Bank Account - 21 Savage",
  "Broccoli - DRAM ft. Lil Yachty",
  "Congratulations - Post Malone ft. Quavo",
  "XO Tour Llif3 - Lil Uzi Vert",
  "Bad and Boujee - Migos ft. Lil Uzi Vert",
  "Mask Off - Future",
  "Panda - Desiigner",
  "Racks in the Middle - Nipsey Hussle",
  "Thotiana - Blueface",
  "A Milli - Lil Wayne",
  "Trap Queen - Fetty Wap",
  "Black Beatles - Rae Sremmurd ft. Gucci Mane",
  "Tunnel Vision - Kodak Black",
  "Life Is Good - Future ft. Drake",
  "Sunflower - Post Malone & Swae Lee",
  "Antidote - Travis Scott",
  "Look What You Made Me Do - Taylor Swift",
  "Freaky Friday - Lil Dicky ft. Chris Brown",
  "Rake It Up - Yo Gotti ft. Nicki Minaj",
  "Best I Ever Had - Drake",
  "Started From the Bottom - Drake",
  "Alright - Kendrick Lamar",
  "N.Y. State of Mind - Nas",
  "Regulate - Warren G ft. Nate Dogg",
  "Gin and Juice - Snoop Dogg",
  "California Love - 2Pac ft. Dr. Dre",
  "Hypnotize - The Notorious B.I.G.",
  "Ms. Jackson - OutKast",
  "Hey Ya! - OutKast",
  "Forgot About Dre - Dr. Dre ft. Eminem",
  "It Was A Good Day - Ice Cube",
  "Still D.R.E. - Dr. Dre ft. Snoop Dogg",
  "Get Low - Lil Jon & The East Side Boyz ft. Ying Yang Twins",
  "Crank That (Soulja Boy) - Soulja Boy",
  "This Is America - Childish Gambino",
  "Money Longer - Lil Uzi Vert",
  "Industry Baby - Lil Nas X ft. Jack Harlow",
    ],
  "Hip-Hop": [
  "Rapper's Delight - The Sugarhill Gang",
  "The Message - Grandmaster Flash and the Furious Five",
  "Fight the Power - Public Enemy",
  "Straight Outta Compton - N.W.A",
  "Nuthin' but a 'G' Thang - Dr. Dre ft. Snoop Dogg",
  "Juicy - The Notorious B.I.G.",
  "C.R.E.A.M. - Wu-Tang Clan",
  "Dear Mama - 2Pac",
  "99 Problems - Jay-Z",
  "Big Poppa - The Notorious B.I.G.",
  "The Real Slim Shady - Eminem",
  "Ignition (Remix) - R. Kelly",
  "Lollipop - Lil Wayne",
  "Trip - Ella Mai",
  "Runaway - Kanye West ft. Pusha T",
  "Crazy in Love - Beyoncé ft. Jay-Z",
  "Get Ur Freak On - Missy Elliott",
  "No Diggity - Blackstreet ft. Dr. Dre",
  "It's Tricky - Run-D.M.C.",
  "Killing Me Softly - Fugees",
  "Fantasy - Mariah Carey ft. Ol' Dirty Bastard",
  "Hip Hop Hooray - Naughty by Nature",
  "Jump Around - House of Pain",
  "Shook Ones, Pt. II - Mobb Deep",
  "The Next Episode - Dr. Dre ft. Snoop Dogg",
  "Drop It Like It's Hot - Snoop Dogg ft. Pharrell",
  "Hate It or Love It - The Game ft. 50 Cent",
  "Grindin' - Clipse",
  "Through the Wire - Kanye West",
  "Slow Jamz - Twista ft. Kanye West & Jamie Foxx",
  "Neck of the Woods - Pusha T",
  "Alright - Kendrick Lamar",
  "N.Y. State of Mind - Nas",
  "One Mic - Nas",
  "Ether - Nas",
  "How We Do - The Game ft. 50 Cent",
  "Wild Thoughts - DJ Khaled ft. Rihanna & Bryson Tiller",
  "Truffle Butter - Nicki Minaj, Drake & Lil Wayne",
  "Superbass - Nicki Minaj",
  "Formation - Beyoncé",
  "Alright - Logic",
  "1-800-273-8255 - Logic ft. Alessia Cara & Khalid",
  "Loyal - Chris Brown ft. Lil Wayne & Tyga",
  "No Type - Rae Sremmurd",
  "Look Alive - BlocBoy JB ft. Drake",
  "Deja Vu - Post Malone ft. Justin Bieber",
  "Big Bank - YG ft. 2 Chainz, Big Sean & Nicki Minaj",
  "Ric Flair Drip - Offset & Metro Boomin",
  "T-Shirt - Migos",
  "Slippery - Migos ft. Gucci Mane",
    ],
  "R&B": [
  "Snooze - SZA",
  "Damage - H.E.R.",
  "Best Part - Daniel Caesar ft. H.E.R.",
  "Kiss Me More - Doja Cat ft. SZA",
  "Nights - Frank Ocean",
  "Redbone - Childish Gambino",
  "Location - Khalid",
  "Peaches - Justin Bieber ft. Daniel Caesar & Giveon",
  "Heartless - The Weeknd",
  "Adorn - Miguel",
  "Skate - Silk Sonic",
  "Cuff It - Beyoncé",
  "Cranes in the Sky - Solange",
  "Water - Tyla",
  "Boy's a Liar - PinkPantheress ft. Ice Spice",
  "Escapism - RAYE ft. 070 Shake",
  "Motion - Ella Mai ft. Roddy Ricch",
  "Wait for U - Future ft. Drake & Tems",
  "Selfish - Justin Timberlake",
  "Sunday Best - Surfaces",
  "Best Interest - Tyler, The Creator",
  "Heartbreak Anniversary - Giveon",
  "Telepatía - Kali Uchis",
  "Type Shit - Future, Travis Scott, Playboi Carti",
  "On My Mama - Victoria Monét",
  "Anti-Hero - Taylor Swift",
  "Wildflower - Billie Eilish",
  "Chosen - Blxst & Tyga",
  "Freaknik - Lil Baby ft. Fridayy",
  "Take You Down - Chris Brown",
  "Come Thru - Summer Walker & Usher",
  "Wonders - Coi Leray",
  "Bags - Clairo",
  "It's Him - Jesse Reyez",
  "Right Now - Kelela",
  "Focus - Ari Lennox",
  "MOOD 4 EVA - Beyoncé, Jay-Z, Childish Gambino & Oumou Sangaré",
  "Hurricane - Kanye West ft. Lil Durk & The Weeknd",
  "Lost - Dvsn",
  "Pure/Honey - FKA twigs",
  "Marigold - Mahalia",
  "Solar Power - Lorde",
  "Ivy - Frank Ocean",
  "Reminder - The Weeknd",
  "Godspeed - Frank Ocean",
  "Roll Some Mo - Snoh Aalegra",
  "Situationship - Snoh Aalegra",
  "Special Interest - Wallice",
  "Come Home - Anderson .Paak ft. André 3000",
  "Am I Wrong - Anderson .Paak ft. ScHoolboy Q",
    ],
  Gospel: [
  "Amazing Grace - Traditional",
  "How Great Thou Art - Traditional",
  "Great Is Thy Faithfulness - Thomas O. Chisholm",
  "Oh Happy Day - Edwin Hawkins Singers",
  "Total Praise - Richard Smallwood",
  "I Need You to Survive - Hezekiah Walker",
  "Never Would Have Made It - Marvin Sapp",
  "Way Maker - Sinach",
  "Goodness of God - Bethel Music / CeCe Winans",
  "Break Every Chain - Tasha Cobbs Leonard",
  "Alabaster Box - CeCe Winans",
  "Take Me to the King - Tamela Mann",
  "Every Praise - Hezekiah Walker",
  "Speak to My Heart - Donnie McClurkin",
  "Stand - Donnie McClurkin",
  "This Is Amazing Grace - Phil Wickham",
  "10,000 Reasons (Bless the Lord) - Matt Redman",
  "Oceans (Where Feet May Fail) - Hillsong United",
  "Great Are You Lord - All Sons & Daughters",
  "My Testimony - Marvin Sapp",
  "You Are Good - William McDowell",
  "Same God - Elevation Worship",
  "Won't He Do It - Koryn Hawthorne",
  "Fill Me Up - Tamela Mann",
  "Your Spirit - Tasha Cobbs Leonard ft. Kierra Sheard",
  "Jireh - Elevation Worship / Maverick City Music",
  "Trust in You - Anthony Brown & Group Therapy",
  "Best Thing - Todd Dulaney",
  "Great Is Your Mercy - Donnie McClurkin & Yolanda Adams",
  "I Give Myself Away - William McDowell",
  "Not Today - Hezekiah Walker",
  "What He's Done - Bri Babineaux",
  "Do It Again - Elevation Worship",
  "Battle Belongs - Phil Wickham",
  "Same Power - Jekalyn Carr",
  "Reckless Love - Cory Asbury",
  "Firm Foundation (He Won't) - Cody Carnes / Maverick City Music",
  "I Won't Take It - Tim Bowman Jr.",
  "Overflow - Maverick City Gospel Choir",
  "Now Behold the Lamb - Kirk Franklin",
  "Talking to Jesus - Maverick City Music / Kirk Franklin",
  "Champion - Maverick City Music",
  "Promises - Maverick City Music / Joe L Barnes / Naomi Raine",
  "Refuge (My Firm Foundation) - Maverick City Music",
  "In Jesus Name (God of Possible) - Katy Nichole",
  "Thank You Jesus for the Blood - Charity Gayle",
  "See a Victory - Elevation Worship",
  "Graves Into Gardens - Elevation Worship",
  "Nobody Like You Lord - Chandler Moore & KJ Scriven",
  "Fear Is Not My Future - Maverick City Music",
  "Bless Me - Charlie Wilson & Marvin Sapp",
  "It's Working - Jekalyn Carr",
  "Level - Anthony Brown & Group Therapy",
  "Beautiful Grace - William McDowell",
  "Chasing You - Maverick City Music",
  ],
};